apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp100g-p1
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "mellanox_100g_p1",
                "selectors": {
                    "pciAddresses": ["0000:04:00.0",
                                     "0000:05:00.0",
                                     "0000:0b:00.0",
                                     "0000:0c:00.0",
                                     "0000:0d:00.0",
                                     "0000:14:00.0",
                                     "0000:1b:00.0",
                                     "0000:1c:00.0"]
                }
            }
        ]
    }

